# Generated by Django 3.0.8 on 2020-07-23 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covid19',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('confirmed', models.IntegerField(default=0)),
                ('active', models.IntegerField(default=0)),
                ('recovered', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('new_cases', models.IntegerField(default=0)),
                ('new_deaths', models.IntegerField(default=0)),
                ('updated_on', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
    ]
