# Generated by Django 3.0.8 on 2020-08-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20200723_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid19',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
