# Generated by Django 3.0.8 on 2020-08-23 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20200803_0804'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Covid19',
        ),
    ]
